### ISSUE TITLE
[Feature Request] Add support for custom language

### ISSUE THREAD

**Issue by MrBoombastic** [tsamaya/opencage-api-client#18]
Please add support for languages other than English. Thanks.

**Comment by tsamaya** [comment]
Hi,
the `language` support is builtin the OpenCage API : https://opencagedata.com/api#language

Then you can use for both geocoding and reverse geocoding the optional parameter `language`:
```
opencage
  .geocode({ q: '45.188529 5.724524', language: 'fr' })
  .then(data => {
    console.log('reverse geocode fr -------------------------');
    console.log(JSON.stringify(data));
  })
  .catch(error => {
    console.log('error', error.message);
  });

```
Hope this helps
