### ISSUE TITLE
Opencage options ex. Proximity

### ISSUE THREAD

**Issue by jbroomer** [tsamaya/opencage-api-client#24]
Hi! I am very grateful for this package as it has made it very easy to add the opencage API to my project however, I wanted to use the 'proximity' option that opencage suggests to bias my search results but I cannot see how I would do that with this package. Please let me know!

Thank you:)

**Comment by tsamaya** [comment]
Hi @jbroomer 
thanks for your support; 
if one want to use other input parameter from the official API, one just have to add it in the input object. So here with the 'proximity' and also 'no_annotations':
```js
opencage
  .geocode({
    q: 'rue de la république lyon',
    proximity: '51.952659, 7.632473',
    no_annotations: 1,
    limit: 3,
  })
  .then(data => {
    console.log('geocode with proximity ---------------------------------');
    console.log(JSON.stringify(data));
  })
  .catch(error => {
    console.log('error', error.message);
  });
```

Hope this help

**Comment by tsamaya** [comment]
the code snippet has been added to the sample file : https://github.com/tsamaya/opencage-api-client/blob/master/samples/node-sample.js#L34-L47

**Comment by jbroomer** [comment]
Hmmm, followed that exactly and it didn't seem to work for me! Still shows results from other continents until I have typed nearly the entire location.

**Comment by tsamaya** [comment]
Interesting, are the results different with a direct call to the API ? 
can you, please, share some examples: (q and proximity parameters) ?

**Comment by tsamaya** [comment]
no answer so far, please feel free to reach me out if needed. I am closing the issue now
