### ISSUE TITLE
TypeScript support (type definitions)

### ISSUE THREAD

**Issue by calmonr** [tsamaya/opencage-api-client#36]
I recently created a [project](https://github.com/calmonr/easycarros) and used **OpenCage Geocoder** with a library called `node-geocoder` but it was using a few deprecated dependencies and I decided to use `opencage-api-client` instead.
`opencage-api-client` is pretty straightforward but it doesn't support TypeScript. In order to keep using it I had to create the type definitions.

https://github.com/calmonr/easycarros/blob/master/typings/opencage-api-client.d.ts#L2-L4

Unfortunately I don't have much time now to create a PR on `DefinitelyTyped` so we can have something like `@types/opencage-api-client` but you can do that if you want to support TypeScript by default.

I hope it helps.

**Comment by tsamaya** [comment]
Hi @calmonr, 
I will look into it.

**Comment by tsamaya** [comment]
Hi,
I used your type definition for the geocode function including it directly into this repo (https://github.com/tsamaya/opencage-api-client/commit/fb8e8467ce65230b316e5504ef59df4833e355e7). I would have found weird to add something with `any` on `DefinitelyTyped`.
I will dig a bit more about other published modules. 
Any advices are welcome.

**Comment by calmonr** [comment]
@tsamaya The type definition I created was just to get rid of errors from TypeScript. It would work even using just `declare module 'opencage-api-client'`.

The best way would be something like:

```typescript
declare module 'opencage-api-client' {
  export interface GeocodeInput {
    key?: string
    q: string
    abbrv?: number
    add_request?: number
    bounds?: string
    countrycode?: string
    // ...
  }

  export function geocode(input: GeocodeInput): Promise<any>
}
```

The parameters can be found here: https://opencagedata.com/api#forward

You don't need to specify the type for the response as it will probably be complex. If you are concerned about using `any`, `axios` for example is using it.

https://github.com/axios/axios/blob/0d8765562401910c1c509f6739a3bc558721e123/index.d.ts#L76-L83

**Comment by tsamaya** [comment]
Hi @calmonr , 
I am almost done with the TypeScript typings on this branch: https://github.com/tsamaya/opencage-api-client/tree/feature/support-typescript.
I might leave the return type as `any` for now and will work on it with OpenCageData founders on a later version.

**Comment by calmonr** [comment]
@tsamaya It will work, don't worry about that. Feel free to ping me if you guys have questions or need help. Keep up the good work :+1:

**Comment by tsamaya** [comment]
New release v0.8.0 published on npm adding the TypeScript support with this PR #39
